# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
<!DOCTYPE html>
<html>
    <head>
        <title>
        I Need To Remember
        </title>
        <link href="main.css" rel="stylesheet" type="text/css">
    </head>
        
        <body>
            <div class="menu">
                <a class="active" href="index.html">Home</a>
                <a href="about.html">About</a>
                <a href="contact.html">Contact</a>
                <a href="faq.html">FAQ</a>
                <input type="text" placeholder="Search..">
            </div>
            <h1>I need to remember how to code because now I want to be able to do freelance work and start making MONEY with this shit.</h1>
        
        
        
        
        
        
        
        
        
        
        
        </body>

</html>
